version: '3.8'

services: 
  mongodb:
    image: mongo:latest
    restart: always
    environment:
    - PUID=1000
    - PGID=1000
    ports:
    - 27018:27017
    volumes:
      - mongo_data:/data/db
    
volumes:
  mongo_data: {}